name: Build

on:
  push: 
    branches: []
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    name: Build
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup Go
        id: go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.22
      # - name: Install dependency
      #   run: if [ $(uname) == "Darwin" ]; then brew install openssl ;fi
      - name: Build
        run: make build

  push_to_docker_latest:
    name: Push master code to docker latest image
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      # QEMU is used to simulate different architecture
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ahuig
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ahuig/selfhttps:latest
      - name: Show image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
